corrected the first task and completed the second task
Evgeni121/tasks pull request #2
Opened 2022-12-15 10:12 UTC by Evgeni121

2022-12-15 11:53 UTC, ak-itacademy requested changes

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +        div, int_div, rem = None, None, None
тогда уж тайпинг должен быть Tuple[Optional[float], Optional[float], Optional[float]]
а вообще ничего страшного в делении на ноль нет
можно оставлять как есть без обработки исключения
так вы меняете общепринятую в нативном питоне парадигму
пользователь скорее будет ожидать исключения, чем того, что результат нужно проверить на None, если вдруг что-то пошло не так

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +        return clip(value, a_min=low, a_max=high)
можно и так, но переделайте все же через if :)

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +    return clip(value, a_min=high, a_max=low) if low > high else clip(value, a_min=low, a_max=high)
а вот здесь вместо clip уже можно использовать написанную вами clamp

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +from numpy import clip
импорты лучше делать в шапке файла

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +        return None
верните просто +/-inf
в формате ведь есть такое значение и оно абсолютно валидно

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +            man = int((1 << 23) * value)
можно просто присвоить уже посчитанное число, оно ведь всегда фиксированно

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_1.py
> +    return first if (first - last) & (1 << 32) else last
сделать можно без использования условных операторов

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        my_list.append(type(n))
можно и так, но слишком громоздко, слишком много лишних действий
попробуйте использовать сразу tuple и map в одной строке

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    my_full_type_list = []
list - очень плохо, поиск имеет линейную сложность
используйте сразу же дикт

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        type_ = str(type(value))
не нужно преобразовывать в строку

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +
вот это вот прямо совсем что-то жуткое

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    return my_dict
рекомендую использовать вместо list сразу же dict и добавлять значения к списку, созданному с помощью dict.setdefault[xxx, []]

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        if cnt % 2 or text[i] == "*":
можно устанавливать флаг в True и False и не делить каждый раз на 2

2022-12-15 11:53 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    return result
очень сложное и не всегда работающее решение
попробуйте сделать либо через split/join, что проще, либо через конечные автоматы, что сложнее, но по скорости работы быстрее

2022-12-16 08:50 UTC, Evgeni121 reviewed
Исправлены замечания

2022-12-17 14:03 UTC, ak-itacademy requested changes

2022-12-17 14:03 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return dict.fromkeys(values, default)
неправильно
попробуйте в default передать [], потом модифицируйте любой из списков словаря и посмотрите, что произойдет с остальными

2022-12-17 14:03 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    first.update(second)
входные переменные модифицировать нельзя

2023-01-04 14:27 UTC, ak-itacademy requested changes

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +        if value and value not in my_dict.values():
Опять же, не будет работать со значениями False, 0 и т. д.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return dict(my_list)
Лучше использовать dict comprehension и записать все в одну строчку.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return dict(my_list)
Опять же, используйте list и sorted, чтобы записать в одну строчку.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return dict(my_list)
Аналогично в одну строку.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return {"number of numbers:": amount}
Используйте sum и просто верните число.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return my_dict
Это хорошее решение, но попробуйте придумать какое-нибудь альтернативное, исходя из того, что у вас передается список.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +    return my_dict
Для произвольных итерируемых объектов это идеальное решение.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    my_type_list = {}
`_list` - немного странное именование для словаря.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        my_type = str(type(value))[8:-2]
Вовсе не нужно переводить тип в строку и, тем более, делать срез.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        my_type_list[my_type].append([key, value])
Можно объединить в одну строку.

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    return result
Не будет работать как минимум для случаев вроде "Sensor-*0*: *1*C".

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +    def __init__(self, value: float or "LengthUnits", conversion_rate: float):
Union[float, "LengthUnits"]

2023-01-04 14:27 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        return f"{value} mm"
В целом неплохо и правильно, но гораздо лучше, если любой тип будет хранить значения в миллиметрах. И только при преобразованию к строке и т. д. использовался множитель для представления в нужной размерности. То есть обратная ситуация тому, что вы сделали.

2023-01-08 12:00 UTC, ak-itacademy requested changes
Очень хорошо, но нужно еще парочку мелочей исправить.

2023-01-08 19:14 UTC, ak-itacademy approved these changes
Есть мелкие недоработки, но в целом хорошо все. Можно мержить.

2023-01-08 22:25 UTC, ak-itacademy requested changes

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +        my_dict[my_type].append([key, value]) if my_type in my_dict else my_dict.setdefault(my_type, [[key, value]])
Просто my_dict.setdefault(type(value), []).append([key, value])

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    my_list = text.split()
Для чего нужно делить строку на части, используя пробел?

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    return result
Вот этот весь код рассчитан на простые случаи.
Попробуйте вариант "\*year\*/\*month\*/\*day\*"

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +    def __init__(self, value: Union[float, "LengthUnits"], conversion_rate: float):
Лучше определить conversion_rate аналогично UNIT_NAME в каждом классе.

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        self.__conversion_rate = float(conversion_rate)
float() - лишнее.

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        self.__value = float(value) * self.__conversion_rate if isinstance(value, float) or isinstance(value, int) \
Лучше использовать либо type(xxx) in (yyy, zzz), либо isinstance(xxx, (yyy, zzz)).

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +    def __add__(self, another):
Если уже начали использовать тайпинги, то стоит продолжать дальше.

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        return self
Общая для всех схожих методов ошибка. Это __iadd__ может модифицировать сам объект, а __add__ не может, он должен просто что-то вернуть. Либо отношение, либо новый объект.

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        return self.__conversion_rate
Используйте здесь везде @property. Соответственно, set_value вообще стоит удалить.

2023-01-08 22:25 UTC, ak-itacademy commented on tasks/task_3_classes.py
> +        return f"{value / conversion_rate} mm"
Зачем везде дублировать этот код? Можно перенести в LengthUnits.

2023-01-09 11:48 UTC, ak-itacademy requested changes

2023-01-09 11:48 UTC, ak-itacademy commented on tasks/task_2_functions.py
> +    result = "".join(my_list)
Попробуйте посмотреть, что будет, если передать строку вроде "year*year*". Добавьте проверку четности индекса.
Также проверка на isdigit, наверное, не лучший вариант. Лучше использовать try и пытаться привести к int. Тогда и с минусом не нужно будет заморачиваться, и такие вот варианты тоже пройдут нормально "* -12  *".
И еще бы добавить вызов исключения, если ни один из вариантов не подошел.

2023-01-10 14:23 UTC, ak-itacademy approved these changes

2023-01-10 16:45 UTC, merged

2023-01-18 15:20 UTC, ak-itacademy requested changes
2 задание с коллекциями почти что закончено и почти отлично, осталось одно изменение.
2 задание с функциями требует изменений.
3 задание требует изменений.

2023-01-18 15:20 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +                + sorted(my_str_list, key=lambda x: ord(x[0])))
Сделайте, пожалуйста, используя sorted и соответствующую функцию для сортировки.

2023-01-18 15:20 UTC, ak-itacademy commented on tasks/task_2_collections.py
> +                + sorted(my_str_list, key=lambda x: ord(x[0]), reverse=True))
Сделайте, пожалуйста, используя sorted и соответствующую функцию для сортировки.